// <auto-generated />
using MailingApi.Layers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MailingApi.Migrations
{
    [DbContext(typeof(MailingApiContext))]
    [Migration("20210221144427_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MailingApi.Models.MailConsumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("con_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConsumerAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("con_address");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("con_groupId");

                    b.HasKey("Id");

                    b.ToTable("MailConsumer");
                });

            modelBuilder.Entity("MailingApi.Models.MailUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usr_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_password");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("usr_name");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[usr_name] IS NOT NULL");

                    b.ToTable("MailUser");
                });

            modelBuilder.Entity("MailingApi.Models.MailingGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grp_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupOwnerId")
                        .HasColumnType("int")
                        .HasColumnName("grp_ownerId");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("grp_name");

                    b.HasKey("Id");

                    b.ToTable("MailingGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
