using MailingApi.Controllers;
using MailingApi.Layers;
using MailingApi.Models;
using MailingApiTests.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;

namespace MailingApiTests
{
    [TestClass]
    public class MailingcontrollerTests
    {
        private static MailingController controller;
        private static BuisnessLayer buisness;

        [ClassInitialize]
        public static void Initialize(TestContext _)
        {
            var options = new DbContextOptionsBuilder<MailingApiContext>().UseInMemoryDatabase(databaseName: "MailDatabase")
                .ConfigureWarnings(x => x.Ignore(InMemoryEventId.TransactionIgnoredWarning)).Options;
            var context = new MailingApiContext(options);
            buisness = new BuisnessLayer(context);
            controller = new MailingController(buisness);
            
            var user = BuissnesTestHelper.CreateBuissnesModelUser("TestUser", "Password");
            var userId = buisness.RegisterUser(user);
            var emails = new List<string> { "a@a.com", "b@b.com" };
            var model = BuissnesTestHelper.CreateBuissnessModelGroup(userId, "testName", emails);
            var model2 = BuissnesTestHelper.CreateBuissnessModelGroup(userId, "testName2", emails);
            buisness.SaveBuissnesModelGroup(model);
            buisness.SaveBuissnesModelGroup(model2);
        }

        #region Get
        [DataRow(-1)]
        [DataRow(10)]
        [TestMethod]
        public void GetGroupByIdShoulReturnNotFound(int groupId)
        {
            var expected = new NotFoundResult();
            var actual = controller.GetGroupById(groupId) as NotFoundResult;
            Assert.AreEqual(expected.GetType(), actual.GetType());
            Assert.AreEqual(expected.StatusCode, actual.StatusCode);
        }
        [TestMethod]
        [DataRow(1)]
        [DataRow(2)]
        public void GetGroupByIdShoulReturnOK(int groupId)
        {
            var expectedGroup = buisness.GetBuissnesModel(groupId);
            var actualGroup = (controller.GetGroupById(groupId) as OkObjectResult).Value as BuissnessModelGroup;
            BuissnesTestHelper.CompareBuissnessModelGroup(expectedGroup, actualGroup);
        }
        #endregion
        #region Post
        [TestMethod]
        public void PostNewGroupShoulReturnUnauthorized()
        {
            var emails = new List<string> { "email1Created", "email2Created" };
            var group = BuissnesTestHelper.CreateBuissnessModelGroup(1, "CreatedName", emails);

            var expected = new UnauthorizedResult();
            var actual = controller.PostNewGroup(group) as UnauthorizedResult;
            Assert.AreEqual(expected.GetType(), actual.GetType());
            Assert.AreEqual(expected.StatusCode, actual.StatusCode);
        }
        [TestMethod]
        public void PostNewGroupShoulReturnCreated()
        {
            var emails = new List<string> { "email1Created", "email2Created" };
            var expectedGroup = BuissnesTestHelper.CreateBuissnessModelGroup(1, "CreatedName", emails);

            var result = controller.PostNewGroup(expectedGroup) as CreatedResult;
            var id = (int)result.Value;
            var actualGroup = buisness.GetBuissnesModel(id);
            expectedGroup.Id = actualGroup.Id; // get generated by database Id
            BuissnesTestHelper.CompareBuissnessModelGroup(expectedGroup, actualGroup);

        }
        #endregion
        #region Put
        [TestMethod]
        public void PutShoulReturnCreated()
        {
        }

        [TestMethod]
        public void PutShoulReturnNotFound()
        {
        }

        [TestMethod]
        public void PutShoulReturnOK()
        {
        }
        #endregion
        #region Delete
        [TestMethod]
        public void DeleteShoulReturnNotFound()
        {
        }

        [TestMethod]
        public void DeleteShoulReturnOK()
        {
        }
        #endregion
    }
}
